### ISSUE TITLE
Broken Follower Count

### ISSUE THREAD

**Issue by bgiesing** [dam0un/dam0un.live#1]
Thanks for updating the code of the template to work with the new API, I used your fork to fix a site I manage for another streamer.

I can't get any follower count to show when running your code as is or with a different Twitch streamer but it's showing fine on your actual website even though it should be the same code in this repository. Any ideas on how to fix?

**Comment by damoun** [comment]
Hi @bgiesing,

Thanks for the issue.
It seems that I forgot to push my last change on the master branch.

Could you rebase you fork and try again ?

**Comment by bgiesing** [comment]
Yep that fixed it
